name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 104.248.85.224
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd projects/backend-new
          git pull
          npm install
          npm run build
          pm2 restart api
