name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build  # Измените команду сборки, если она отличается

    - name: Deploy to Droplet
      run: |
        ssh-keyscan 104.248.85.224 >> ~/.ssh/known_hosts
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -C "shashkovdanil@gmail.com"
        ssh-add ~/.ssh/id_rsa
        rsync -r --delete-after -e "ssh -o StrictHostKeyChecking=no" ./dist/ root@104.248.85.224:projects/backend-new

    - name: Restart App on Droplet
      run: ssh root@104.248.85.224 "npm run start:prod"
