name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 104.248.85.224
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd projects/backend-new
          git pull
          npm install
          npm run build
          pm2 restart api

    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Restart App on Droplet
    #   run: ssh -o StrictHostKeyChecking=no root@104.248.85.224 "cd projects/backend-new && git pull && bash restart.sh"
