name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Измените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh/
        chmod 700 ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
        ssh-keyscan 104.248.85.224 >> ~/.ssh/known_hosts
        ls -la ~/.ssh
        ssh root@104.248.85.224

    - name: Deploy to Droplet
      run: |
        rsync -r --delete-after -e "ssh -o StrictHostKeyChecking=no" ./dist/ root@104.248.85.224:projects/backend-new

    - name: Restart App on Droplet
      run: ssh root@104.248.85.224 "npm run start:prod"
